package com.orcchg.arkanoid.surface;

public class Levels {  
  public static String[] get(int index) {
    if (index < 0 || index >= TOTAL_LEVELS) {
      index = 0;
    }
    return levels[index];
  }
  
  public static String[] get(int index, String state) {
    if (state.isEmpty()) {
      return get(index);
    } else {
      return state.split("!+");
    }
  }
  
  private static final String[] L0 = new String[] {"",
                                                   "",
                                                   "",
                                                   "",
                                                   "  SSSSSS  ",
                                                   "  SSSSSS  ",
                                                   "  SSSSSS  ",
                                                   "  SSSSSS  ",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   ""};
  
//  private static final String[] L0 = new String[] {"",
//                                                   "",
//                                                   "",
//                                                   "",
//                                                   "",
//                                                   "        CT",
//                                                   "       JT",
//                                                   "      RT",
//                                                   "     WT",
//                                                   "    PT",
//                                                   "   LT",
//                                                   "  IT",
//                                                   " BT",
//                                                   "ST",
//                                                   "T",
//                                                   "",
//                                                   "",
//                                                   "",
//                                                   "",
//                                                   "",};
  
//  private static final String[] L0 = new String[] {"TTTTTTTTTT",
//                                                   "",
//                                                   "",
//                                                   "",
//                                                   "TTTTTTTT",
//                                                   "",
//                                                   "",
//                                                   "",
//                                                   "  TTTTTTTT",
//                                                   "",
//                                                   "",
//                                                   "",
//                                                   "TTTTTTTT",
//                                                   "",
//                                                   "",
//                                                   "",
//                                                   "  TTTTTTTT",
//                                                   "",
//                                                   "",
//                                                   "",
//                                                   "TTTTTTTT",
//                                                   "",
//                                                   "",
//                                                   "",
//                                                   ""};
  
//private static final String[] L0 = new String[] {"",
//                                                 "",
//                                                 "",
//                                                 "",
//                                                 "",
//                                                 "    ",
//                                                 "",
//                                                 "",
//                                                 "        ",
//                                                 "",
//                                                 "",
//                                                 "",
//                                                 "",
//                                                 "",
//                                                 "",
//                                                 "",
//                                                 "   ",
//                                                 "",
//                                                 "       H",
//                                                 "",
//                                                 "",
//                                                 "",
//                                                 "",
//                                                 "",
//                                                 ""};
  
  private static final String[] L1 = new String[]{"",
                                                  "",
                                                  "",
                                                  "",
                                                  "  BBBBBB  ",
                                                  "  BSSSSB  ",
                                                  "  BSSSSB  ",
                                                  "  BSSSSB  ",
                                                  "  BSSSSB  ",
                                                  "  BBBBBB  ",
                                                  "",
                                                  "",
                                                  "",
                                                  "",
                                                  "",
                                                  "",
                                                  "",
                                                  "",
                                                  "",
                                                  ""};
  
  private static final String[] L2 = new String[]{"",
                                                  "",
                                                  "",
                                                  "",
                                                  "",
                                                  "",
                                                  "FFFFFFFFFF",
                                                  "FFFFFFFFFF",
                                                  "FFFFFCFFFF",
                                                  "FFFFCCFFFF",
                                                  "FFFCCCCFFF",
                                                  "FFCCCCCCFF",
                                                  "FCCCCCCCCF",
                                                  "CCCCCCCCCC",
                                                  "BBBBBBBBBB",
                                                  "",
                                                  "",
                                                  "",
                                                  "",
                                                  ""};
  
  private static final String[] L3 = new String[]{"",
                                                  "",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "",
                                                  "",
                                                  "",
                                                  "",
                                                  ""};
  
  private static final String[] L4 = new String[] {" S    SS  ",
                                                   "S   SS    ",
                                                   " S S      ",
                                                   "  S    SS ",
                                                   "   S  S  S",
                                                   "    ES    ",
                                                   "   SR S   ",
                                                   "  S R  S  ",
                                                   "   SR   S ",
                                                   "    R     ",
                                                   "    R   S ",
                                                   "    R SS  ",
                                                   "    RS    ",
                                                   "   RRR    ",
                                                   "   RRR    ",
                                                   " CCCCCCC  ",
                                                   "CCCCCCCCCC",
                                                   "",
                                                   ""};
  
  private static final String[] L5 = new String[]{"",
                                                  "",
                                                  "",
                                                  "         S",
                                                  "        SB",
                                                  "       SBB",
                                                  "      SBBB",
                                                  "     SBBBB",
                                                  "    SBBBBA",
                                                  "   SBBBBAI",
                                                  "    SBBBBA",
                                                  "     SBBBB",
                                                  "      SBBB",
                                                  "       SBB",
                                                  "        SB",
                                                  "         S",
                                                  "",
                                                  "",
                                                  "",
                                                  "",
                                                  ""};
  
  private static final String[] L6 = new String[]{"",
                                                  "",
                                                  "",
                                                  "    T     ",
                                                  "   TSB    ",
                                                  "  TSSSB   ",
                                                  " TSSSSSB  ",
                                                  "  TSSSSB  ",
                                                  "   TSSB   ",
                                                  "    TB    ",
                                                  "     B    ",
                                                  "    BST   ",
                                                  "   BSSST  ",
                                                  "  BSSSSST ",
                                                  "   BSSST  ",
                                                  "    BBT   ",
                                                  "     B    ",
                                                  "",
                                                  "",
                                                  ""};
  
  private static final String[] L7 = new String[] {"",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "AAAAAAAAAA",
                                                   "AASSSSSSAA",
                                                   "AAAAAASSAA",
                                                   "AASSSSSSAA",
                                                   "AASSAAAAAA",
                                                   "AASSSSSSAA",
                                                   "AAAAAAAAAA",
                                                   "BBBBBBBBBB",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   ""};
  
  private static final String[] L8 = new String[] {"",
                                                   "",
                                                   "",
                                                   "",
                                                   "WJWWWWWWWJ",
                                                   "JWJWWWWWJW",
                                                   "WWWJWWWJWW",
                                                   "WWWWJWJWWW",
                                                   "WWWWWJWWWW",
                                                   "WWWWJWJWWW",
                                                   "WWWJWWWJWW",
                                                   "JWJWWWWWJW",
                                                   "WJWWWWWWWJ",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   ""};
  
  private static final String[] L9 = new String[] {"",
                                                   "",
                                                   "TTTTTTTTTT",
                                                   " S      S",
                                                   " LBBBBBBL ",
                                                   " LBBBBBBL ",
                                                   " LBBBBBBL ",
                                                   " LBBBBBBL ",
                                                   " LBBBBBBL ",
                                                   " LBBBBBBL ",
                                                   "",
                                                   "",
                                                   "FFFFFFFFFF",
                                                   "FFFFFFFFFF",
                                                   "FFFFFFFFFF",
                                                   "SSSSSSSSSS",
                                                   "",
                                                   "",
                                                   "",
                                                   ""};
  
  private static final String[] L10 = new String[] {"    TT    ",
                                                    "    II    ",
                                                    "   L  L   ",
                                                    "  L    L  ",
                                                    " T      T ",
                                                    "  TTFFTT  ",
                                                    " FFFFFFFF ",
                                                    " TTFFFFTT ",
                                                    " GGTTTTGG ",
                                                    " RRJJJJRR ",
                                                    "  IIIIII  ",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L11 = new String[] {"FFFIIIIFFF",
                                                    "FFSBBBBSFF",
                                                    "FSBB  BBSF",
                                                    "SBB    BBS",
                                                    "BB      BB",
                                                    "FFFFFFFFFF",
                                                    "FFFFFFFFFF",
                                                    "FFFFFFFFFF",
                                                    "CCCCCCCCCC",
                                                    "CCCCCCCCCC",
                                                    "WWWWWWWWWW",
                                                    "WWWWWWWWWW",
                                                    "WWWWWWWWWW",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L12 = new String[] {" PP  I    ",
                                                    "P  P  I   ",
                                                    " P  L  P  ",
                                                    "  P  L  P ",
                                                    "P  P  T  P",
                                                    " L  I  P  ",
                                                    "  L  I  P ",
                                                    "   L  I  P",
                                                    "    L  T  ",
                                                    "B  T  T  S",
                                                    " B  T  T S",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L13 = new String[] {"    LL    ",
                                                    "    LL    ",
                                                    "    LL    ",
                                                    "    LL    ",
                                                    "VGGGLLGGGV",
                                                    "VGGGGGGGGV",
                                                    "VGGGGGGGGV",
                                                    "VGGTTTTGGV",
                                                    "VGGGGGGGGV",
                                                    "VGGGGGGGGV",
                                                    "VGGVVVVGGV",
                                                    "TPPIIIIPPT",
                                                    "T        T",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L14 = new String[] {"P   U    P",
                                                    "P        P",
                                                    "P        P",
                                                    "P        P",
                                                    "P        P",
                                                    "TT  TTT  P",
                                                    "         P",
                                                    "         P",
                                                    "         P",
                                                    "  TTT   TT",
                                                    "",
                                                    "",
                                                    "",
                                                    "TTT   TT  ",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L15 = new String[] {"    DD    ",
                                                    "  N TT N  ",
                                                    "  TTKKTT  ",
                                                    "  BBBBBB  ",
                                                    " BBBBBBBB ",
                                                    "BBRRRRRRBB",
                                                    "BRRRJJRRRB",
                                                    "BBBBJJBBBB",
                                                    "BZZJJJJZZB",
                                                    "BZZJJJJZZB",
                                                    "BBJRRRRJBB",
                                                    "BJJBRRBJJB",
                                                    "JJZBBBBZJJ",
                                                    "JJJJBBJJJJ",
                                                    "BBJJRRJJBB",
                                                    "BJJRRRRJJB",
                                                    " BJJBBJJB ",
                                                    "FBBBYYBBBF",
                                                    "FFBBFFBBFF",
                                                    ""};
  
  private static final String[] L16 = new String[] {"",
                                                    "",
                                                    "         G",
                                                    "        GG",
                                                    "       GGG",
                                                    "      GGGL",
                                                    "     GGGLL",
                                                    "    GGGLLL",
                                                    "  GGLLLLLL",
                                                    "GGGLLLLLLL",
                                                    "GGGGGLLLLL",
                                                    " GGGGGLLLL",
                                                    "   GGGGGLL",
                                                    "     GGGGL",
                                                    "       GGG",
                                                    "        GG",
                                                    "         G",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L17 = new String[] {"  SSSSSS  ",
                                                    "  #XSSX#  ",
                                                    "    SS    ",
                                                    "  SSSSSS  ",
                                                    " SXXXXXXS ",
                                                    " SSESSESS ",
                                                    "   S  S   ",
                                                    "",
                                                    "",
                                                    "  #BBBB#  ",
                                                    "",
                                                    " X   X   X",
                                                    " T   T   T",
                                                    " P   P   P",
                                                    " L   L   L",
                                                    " I   I   I",
                                                    " S   S   S",
                                                    " K   K   K",
                                                    "",
                                                    ""};
  
  private static final String[] L18 = new String[] {"XXE    EXX",
                                                    "  P    P  ",
                                                    "  PPPPPP  ",
                                                    "  PPPPPP  ",
                                                    "",
                                                    "  PPPPPP  ",
                                                    "  H    H  ",
                                                    "",
                                                    "    KK    ",
                                                    "  XXXXXX  ",
                                                    "   BBBB",
                                                    " IIIIIIII",
                                                    "  BBBBBB",
                                                    "   SSSS",
                                                    "    SS",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L19 = new String[] {" BPPPB    ",
                                                    "  BPB     ",
                                                    "   B      ",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "      ZZ#D",
                                                    "    ZZD#ZZ",
                                                    "  ZZD#ZZ  ",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L20 = new String[] {"SSSSSSSSES",
                                                    "SSSESSSSSS",
                                                    "SSSSSSSSSS",
                                                    "ESSSSSSSSE",
                                                    "SSSSSSSSSS",
                                                    "SSSSSESSSS",
                                                    "T  R T  RT",
                                                    " TR   TR  ",
                                                    "  T    T  ",
                                                    " R B   BR ",
                                                    "   R   R  ",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L21 = new String[] {"NSSSSDOESN",
                                                    "SSODESSSSS",
                                                    "SSSSSSDOES",
                                                    "SDOESSSSSS",
                                                    "SESSSSSDOE",
                                                    "SOSSSSSSSS",
                                                    "",
                                                    "",
                                                    "",
                                                    "   TYNT   ",
                                                    "   TTTT   ",
                                                    "          ",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L22 = new String[] {"SSSSSESSSS",
                                                    "SSESSSSSES",
                                                    "JJJJJJJJJJ",
                                                    "JJJJJJJJJJ",
                                                    "PPPPPPPPPP",
                                                    "PPPPPPPKPP",
                                                    "LLLLLLLLLL",
                                                    "LLLLLLLLLL",
                                                    "IIIIKIIIII",
                                                    "IIIIIIIIII",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "SKSSSSSSSS",
                                                    "]]]]]]]]]]",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L23 = new String[] {"   P      ",
                                                    "",
                                                    "   E      ",
                                                    "  XXX     ",
                                                    "         X",
                                                    "        X ",
                                                    "       X  ",
                                                    "      X  $",
                                                    "]]]]]]]",
                                                    "",
                                                    "X",
                                                    " X",
                                                    "  X",
                                                    "$  X",
                                                    "   ]]]]]]]",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L24 = new String[] {"TTTTTTTT",
                                                    "        BB",
                                                    "        BB",
                                                    "        PP",
                                                    "",
                                                    "",
                                                    "         E",
                                                    "  VVVVVXXX",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L25 = new String[] {"TTTTTTTTTT",
                                                   "  ISSSSSI ",
                                                   "   IAAAI  ",
                                                   "    IAI   ",
                                                   "     B    ",
                                                   "    FF    ",
                                                   "   FFFF   ",
                                                   "  FFFFFF  ",
                                                   "  XFFFFX  ",
                                                   "   XEEX   ",
                                                   "    XX    ",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   "",
                                                   ""};
  
  private static final String[] L26 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBYBBB",
                                                    "BBBBBBBBBB",
                                                    "BBYBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBYBBB",
                                                    "",
                                                    "XXXXXXXXXX",
                                                    " Y      Y ",
                                                    "BBBBBBBBBB",
                                                    "BBBBYBBBBB",
                                                    "BBBBBBBBBB",
                                                    "BBYBBBBYBB",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L27 = new String[] {"  TTTTT   ",
                                                    " TTJJJTT  ",
                                                    "TTWWWWWTT ",
                                                    "TWWWWWWWTT",
                                                    "WW     WWT",
                                                    "W       WW",
                                                    "         W",
                                                    "BBBBBBBBBB",
                                                    "BBMBBBBMBB",
                                                    "BBBBBBBBBB",
                                                    "BBMBBBBMBB",
                                                    "BBBBBBBBBB",
                                                    "",
                                                    "  M    M  ",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "  M    M  ",
                                                    "",
                                                    ""};
  
  private static final String[] L28 = new String[] {"",
                                                    "LLLLLLQLLL",
                                                    "LLQLLLLLLL",
                                                    "LLLLLLLQLL",
                                                    "LLLQLLLLLL",
                                                    "",
                                                    "",
                                                    "IQIIIIIIII",
                                                    "IIIIIIIQII",
                                                    "IIIIQIIIII",
                                                    "IQIIIIIQII",
                                                    "",
                                                    "",
                                                    "BQBBBBBBQB",
                                                    "BBBBQBBBBB",
                                                    "BBBBBBBBQB",
                                                    "QBBBBBBBBB",
                                                    "BBBBQBBBBB",
                                                    "",
                                                    ""};
  
  private static final String[] L29 = new String[] {"U M     TT",
                                                    "PPPPPPPPPP",
                                                    "PPM",
                                                    "PPPPPPPPPP",
                                                    "       QPP",
                                                    "LLLLLLLLLL",
                                                    "LLM",
                                                    "LLLLLLLLLL",
                                                    "       QLL",
                                                    "IIIIIIIIII",
                                                    "IIM",
                                                    "IIIIIIIIII",
                                                    "       QII",
                                                    "BBBBBBBBBB",
                                                    "BBM",
                                                    "BBBBBBBBBB",
                                                    "       QBB",
                                                    "BBBBBBBBBB",
                                                    "BBM",
                                                    ""};
  
  private static final String[] L30 = new String[] {"  T    T",
                                                    "  TPPEPT",
                                                    "  TPPPPT",
                                                    "  TPPPPT",
                                                    "   TTTT",
                                                    "    FF",
                                                    "    FF",
                                                    "    TT",
                                                    "   TFFT  ",
                                                    " PTFFFFTP ",
                                                    "PLLLLLLLLP",
                                                    "LPLLLLLLPL",
                                                    "PLELLLLELP",
                                                    "LPLLLLLLPL",
                                                    "BBBEBBEBBB",
                                                    "BBB    BBB",
                                                    "CCC    CCC",
                                                    "CCCCCCCCCC",
                                                    "",
                                                    ""};
  
  private static final String[] L31 = new String[] {"  U  U",
                                                    "  B  B",
                                                    "  I  I",
                                                    "  K  K",
                                                    "  S  S",
                                                    "FFFFQFFFFF",
                                                    "SSSQS",
                                                    "SSQSSQSSSS",
                                                    "EST    QSS",
                                                    "PPT    Z T",
                                                    "PT  ZZ  Z",
                                                    "TT  TT ZZ",
                                                    "ET      Z",
                                                    "SST    Z T",
                                                    "PPPPPPPPPP",
                                                    "QQYYQQYYQQ",
                                                    "PPPPPPPPPP",
                                                    "YYQQYYQQYY",
                                                    "",
                                                    ""};
  
  private static final String[] L32 = new String[] {"",
                                                    "     P",
                                                    "    O O",
                                                    "   P N P",
                                                    "  P ZZZ P",
                                                    " PO     OP",
                                                    "  POLLLOP",
                                                    " O PLELP O",
                                                    "    PPP   ",
                                                    " ZZ  Z  ZZ",
                                                    "J  ZZ ZZ",
                                                    " ZZ  N  ZZ",
                                                    "Z  JZ JZ  ",
                                                    " JZ  Z  Z ",
                                                    "Z  Z  Z  Z",
                                                    " ZJ ZZ  Z ",
                                                    "   N  JJ Z",
                                                    "ZJJ Z Z   ",
                                                    "   Z   JZ ",
                                                    "",
                                                    ""};
  
  private static final String[] L33 = new String[] {"",
                                                    "   XTX",
                                                    "  XTUTX",
                                                    " XT   TX",
                                                    "XX  I  TX",
                                                    "XE IQI  XX",
                                                    "XE IMI  EX",
                                                    " X  I   ET",
                                                    "  T",
                                                    "   T",
                                                    "WWWWT",
                                                    "WWWWWP",
                                                    "WWWWWWP",
                                                    "WWWWWWWBBB",
                                                    "WWWWWWWWBB",
                                                    "WWWWWWWWWB",
                                                    "WWWWWWWWWB",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L34 = new String[] {"TTFFTTTFTT",
                                                    "DTFFTDTFTD",
                                                    " TFFT TFT",
                                                    " I  I I I",
                                                    " IIII III",
                                                    " I  I IOI",
                                                    " I  I I I",
                                                    " IKOI IOI",
                                                    " I  I I I",
                                                    " X  X X X",
                                                    " X  X X X",
                                                    "",
                                                    "FFFFFFFFFF",
                                                    "FFFFFFFFFF",
                                                    "FFYFFFFYFF",
                                                    "FFCFFFFCFF",
                                                    "FCCCFFFCCF",
                                                    "CCCCCFCCCC",
                                                    "  M    M",
                                                    "",
                                                    ""};
  
  private static final String[] L35 = new String[] {"",
                                                    "",
                                                    "YYYYYYYYYY",
                                                    "YYYYYYYYYY",
                                                    "YYYYYYYYYY",
                                                    "YYYYYYYYYY",
                                                    "YYYYYYYYYY",
                                                    "   E   E  ",
                                                    "YYYYYYYYYY",
                                                    "YYYYYYYYYY",
                                                    "YYYYYYYYYY",
                                                    "YYYYYYYYYY",
                                                    "YYYYYYYYYY",
                                                    "YYYYYYYYYY",
                                                    "YYYYYYYYYY",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L36 = new String[] {"LLLPPPPLLL",
                                                    "IIEPPPPEII",
                                                    "FFFFFFFFFF",
                                                    "FFFTTTTFFF",
                                                    "FFFFFFFFFF",
                                                    "FFFFFFFFFF",
                                                    "TTTFFFFTTT",
                                                    "FFFFFFFFFF",
                                                    "FFFFFFFFFF",
                                                    "FFFFFFFFFF",
                                                    "FFFFFFFFFF",
                                                    "FFFFFFFFFF",
                                                    "XXXXXXXXXX",
                                                    "MMMMMMMMMM",
                                                    "BBBBBBBBBB",
                                                    "MMMMMMMMMM",
                                                    "BBBBBBBBBB",
                                                    "MMMMMMMMMM",
                                                    "",
                                                    ""};
  
  private static final String[] L37 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "   $TT$",
                                                    "  $TL T$",
                                                    " $TL L T$",
                                                    "$TL   L T$",
                                                    "T  L L   T",
                                                    "   PBP",
                                                    "  PBQBP",
                                                    " PBBBBBP",
                                                    "PBBBQBBBP",
                                                    "QBBBBBBBQP",
                                                    " BBBQBBBBB",
                                                    "BBBBBBBBB",
                                                    " BBBBBBBQB",
                                                    "BBBBQBBBB",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L38 = new String[] {"  Z  D  Z",
                                                    " LIIPMPIIL",
                                                    "   ZPMPZ",
                                                    " LIIPMPIIL",
                                                    "  Z  E  Z",
                                                    "",
                                                    "",
                                                    "    E E",
                                                    "   BB BB",
                                                    "  BBBQBBB",
                                                    "    BBB",
                                                    "  Y  B  Y",
                                                    "  Y     Y",
                                                    "  E     E",
                                                    "  E  S  E",
                                                    "    SSS",
                                                    "  SSSQSSS",
                                                    "   WS SW",
                                                    "    E E",
                                                    ""};
  
  private static final String[] L39 = new String[] {"",
                                                    "B  E  #  D",
                                                    "B  E  #  D",
                                                    "F  F  F  F",
                                                    "F  F  F  F",
                                                    "F  F  F  F",
                                                    "F  F  F  F",
                                                    "F  F  F  F",
                                                    "F  F  F  F",
                                                    "F  F  F  F",
                                                    "F  F  F  F",
                                                    "F  F  F  F",
                                                    "F  F  F  F",
                                                    "C  C  C  C",
                                                    "C  C  C  C",
                                                    "C  C  C  C",
                                                    "C  C  C  C",
                                                    "C  C  C  C",
                                                    "",
                                                    ""};
  
  private static final String[] L40 = new String[] {"     N",
                                                    "  OO   OO",
                                                    "  BB   BB",
                                                    " OBBO OBBO",
                                                    " BBBB BBBB",
                                                    " BBBBOBBBB",
                                                    "  BBBBBBB",
                                                    "  BBBBBBB",
                                                    "  BBBBBBB",
                                                    "   BBBBB",
                                                    "   BBBBB",
                                                    "    BBB",
                                                    "     B",
                                                    "",
                                                    "",
                                                    "ZZZYYYYYZZ",
                                                    "ZZZZYYYZZZ",
                                                    "ZNZZZYZZZZ",
                                                    "",
                                                    ""};
  
  private static final String[] L41 = new String[] {"FXFXFFFFFF",
                                                    "FFFFXFXFFF",
                                                    "FFFFFXFFFF",
                                                    "FFFIFFFFFF",
                                                    "FFFFIFFFFF",
                                                    "FFFFFIFFFF",
                                                    "FFFFFFIFFF",
                                                    "FBBBFFFIFF",
                                                    "FBBBFFFFIF",
                                                    "FBBEFFFFLF",
                                                    "FEBBFFFFLF",
                                                    "FBBBFFJJJJ",
                                                    "FBEBFFJGGJ",
                                                    "FBBBFFJJJJ",
                                                    "FEBBFFJGGJ",
                                                    "SCCCSWWWWS",
                                                    "SCCSSWWWSS",
                                                    "SSCCSSWSSS",
                                                    "SSCSSSSSSS",
                                                    ""};
  
  private static final String[] L42 = new String[] {"YYMZZYUYZZ",
                                                    "ZZZYYZZZYY",
                                                    "YYYZZYYYZZ",
                                                    "YYYZZMYYZZ",
                                                    "ZZZYYZZZYY",
                                                    "ZZZYYZZZYY",
                                                    "YMYZZYYYZZ",
                                                    "YYYZZYYMZZ",
                                                    "YYYZZYYYZZ",
                                                    "ZZZYYZZZYY",
                                                    "ZZZMYZZZYY",
                                                    "ZZZYYZZZYY",
                                                    "YYYYYYYMYY",
                                                    "YYMYYYYYYY",
                                                    "YYYZZZYYZZ",
                                                    "YYYZZZYYZZ",
                                                    "YYYYYYMYYY",
                                                    "YYMYYYYYYY",
                                                    "",
                                                    ""};
  
  private static final String[] L43 = new String[] {"  PPPPPP",
                                                    "",
                                                    "    EE",
                                                    "   XXXX",
                                                    "    DD",
                                                    "",
                                                    "    XX",
                                                    "   MFFM",
                                                    "  MFFFFM",
                                                    " MFFFFFFM",
                                                    "MFFFFFFFFM",
                                                    " MFFFFFFM",
                                                    "  MFFFFM",
                                                    "  TMFFMT",
                                                    "  TFFFFT",
                                                    " TTFFFFTT",
                                                    "TTTFFFFTTT",
                                                    "BBB    BBB",
                                                    "BBB    BBB",
                                                    " P      P"};
  
  private static final String[] L44 = new String[] {"PIIIIIIIIP",
                                                    "PEBFFFFBEP",
                                                    "PBBLLLLBBP",
                                                    "PFFLSSLFFP",
                                                    "PFFLSSLFFP",
                                                    "PFFLFFLFFP",
                                                    "PZZLFFLZZP",
                                                    "PGGLFFLGGP",
                                                    "PGGLZZLGGP",
                                                    "KGGLGG#GGK",
                                                    "PGGLGGLGGP",
                                                    "KFFLGG#FFP",
                                                    "PFFLZZLFFP",
                                                    "PFFLGGLFFP",
                                                    "PZZLGGLZZP",
                                                    "P  LGGL  P",
                                                    "K  #GG#  K",
                                                    "P  LZZL  P",
                                                    "PZZL  LZZP",
                                                    ""};
  
  private static final String[] L45 = new String[] {"U   XXX",
                                                    "",
                                                    "",
                                                    "XXXX",
                                                    "E",
                                                    "",
                                                    "       XXX",
                                                    "         E",
                                                    "    XXX",
                                                    "    E",
                                                    "XXXX",
                                                    "GGGGGGGGGG",
                                                    "GGGGGGGGGG",
                                                    "",
                                                    "",
                                                    "",
                                                    "T T T T T ",
                                                    "",
                                                    "",
                                                    " T T T T T",
                                                    "",
                                                    "B B B B B",
                                                    "",
                                                    " B B B B B",
                                                    ""};
  
  private static final String[] L46 = new String[] {" ZZZZZZZ",
                                                    "Z       Z",
                                                    "Z  ZZZ  Z",
                                                    "Z Z   Z Z",
                                                    "Z Z O Z Z",
                                                    "Z Z Z Z Z",
                                                    "Z Z  Z  Z",
                                                    "Z Z     Z",
                                                    "K  ZZZZZ ",
                                                    "Z        Z",
                                                    " ZZZZZZZ#",
                                                    "",
                                                    " #JJJJJJ",
                                                    "J       J",
                                                    "J  JJJ  J",
                                                    "J J   J J",
                                                    "J J O J J",
                                                    "J J J J J",
                                                    "J J  J  J",
                                                    "J J     J",
                                                    "J  JJJJJ",
                                                    "J        J",
                                                    " JJJJJJJJ",
                                                    "",
                                                    ""};
  
  private static final String[] L47 = new String[] {"",
                                                    "  T $$ T",
                                                    "   T  T",
                                                    "   CTTC",
                                                    "  CCCCCC",
                                                    "CCECCCCECC",
                                                    "CCDCCCCDCC",
                                                    " C CRRC C",
                                                    " CCCRCCCC",
                                                    "  PCCRCP",
                                                    "   PCCP",
                                                    "    II",
                                                    "    SZ  Z",
                                                    "    SZ  S",
                                                    "    SZ S@",
                                                    "  Z SZ S",
                                                    "  S SZS",
                                                    "  @ SZ@",
                                                    "   @@Z",
                                                    " BBWWWWBB",
                                                    " BBBWWBBB",
                                                    " BBBBWBBB",
                                                    " BBQBBQBB",
                                                    " BBBBBBBB",
                                                    ""};
  
  private static final String[] L48 = new String[] {"",
                                                    "",
                                                    " DD DD DD ",
                                                    " EE EE EE ",
                                                    " EEKEEKEE ",
                                                    " KEEEKEEK ",
                                                    "  KEEKEEK",
                                                    "   EEEE",
                                                    "E   PP   E",
                                                    "I   II   I",
                                                    "I IP  PI I",
                                                    "I IP  PI I",
                                                    "I IP  PI I",
                                                    " IIP  PII",
                                                    " IIP  PII",
                                                    "  IP  PI",
                                                    "  IP  PI",
                                                    "  IP  PI",
                                                    "  IP  PI",
                                                    " I      I",
                                                    " I      I",
                                                    " I      I",
                                                    " B      B",
                                                    " B      B",
                                                    ""};
  
  private static final String[] L49 = new String[] {" TTTTTTTT",
                                                    "TT      TT",
                                                    "T        T",
                                                    "          ",
                                                    "     TT   ",
                                                    "    T  T  ",
                                                    "   T    T ",
                                                    "  T     T ",
                                                    "  T     T ",
                                                    "  T  TSST ",
                                                    "  T  T  T ",
                                                    "  T  T  T ",
                                                    "  T  T  T ",
                                                    "  T  T  T ",
                                                    "  T  T  T ",
                                                    "  T  T  T ",
                                                    "  T  T  T ",
                                                    "  T  TUT  ",
                                                    "  T   T   ",
                                                    "  T       ",
                                                    "  T      T",
                                                    "   T    T",
                                                    "    TTTT",
                                                    "",
                                                    ""};
  
  private static final String[] L50 = new String[] {"$   BB   $",
                                                    "   OBBO",
                                                    "  OBEEBO",
                                                    " JB    BJ",
                                                    "JB  ZZ  BJ",
                                                    "B  Z  Z  B",
                                                    "  Z PP Z",
                                                    " Z PT P Z",
                                                    "Z P  T P Z",
                                                    "Z P T  P Z",
                                                    "Z P  T P Z",
                                                    "Z P T  P Z",
                                                    " Z P TP Z",
                                                    "  Z PP Z",
                                                    "   Z  Z",
                                                    "    ZZ",
                                                    "",
                                                    "ZY      YZ",
                                                    " ZYY  YYZ",
                                                    "  ZYYYYZ",
                                                    "   ZTTZ",
                                                    "$   ZZ   $",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L51 = new String[] {"",
                                                    "  TTT",
                                                    "  THT",
                                                    "  T T",
                                                    "",
                                                    "DSD  JJJ",
                                                    "SNS  JNJ",
                                                    "SDS  JJJ",
                                                    "",
                                                    "       BBB",
                                                    "LLL    BNB",
                                                    "LNL    BBB",
                                                    "LLL",
                                                    "      III",
                                                    "      INI",
                                                    " PPP  III",
                                                    " PNP",
                                                    " PPP BBB",
                                                    "     BNB",
                                                    "     BBB",
                                                    "BBB    TTT",
                                                    "BNB    TYH",
                                                    "BBB    T",
                                                    "",
                                                    ""};
  
  private static final String[] L52 = new String[] {"",
                                                    " TT S TT",
                                                    " TSS SST",
                                                    "SS  B  SS",
                                                    "   BHB",
                                                    "SS  B  SS",
                                                    " TSS SST",
                                                    " TT S TT",
                                                    "   K  @@WW",
                                                    "    @@WWZZ",
                                                    "  @@WWZZ",
                                                    "@@WWZZ",
                                                    "WWZZ  K",
                                                    "    SS",
                                                    "  SS  SS",
                                                    "SS  YH  SS",
                                                    "SN  BB  NS",
                                                    "SSSB  BSSS",
                                                    "  B EE B",
                                                    "   B  B",
                                                    "XEX BB XEX",
                                                    "XNX    XNX",
                                                    "XXX    XXX",
                                                    "",
                                                    ""};
  
  private static final String[] L53 = new String[] {"",
                                                    "  T T T T ",
                                                    "  TBT TBT ",
                                                    "  TTT TTT ",
                                                    "",
                                                    "  HS SH HS",
                                                    "",
                                                    "  SH HS SH",
                                                    "",
                                                    "  HS SH HS",
                                                    "",
                                                    "  SH HS SH",
                                                    "",
                                                    "  HS SH HS",
                                                    "",
                                                    "  SH HS SH",
                                                    "",
                                                    " BBB   BBB",
                                                    " B B   B B",
                                                    " B B   B B",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L54 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L55 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L56 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L57 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L58 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L59 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L60 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[][] levels = {L0, L1, L2, L3, L4, L5, L6, L7, L8, L9,
                                            L10, L11, L12, L13, L14, L15, L16, L17, L18,
                                            L19, L20, L21, L22, L23, L24, L25, L26, L27,
                                            L28, L29, L30, L31, L32, L33, L34, L35, L36,
                                            L37, L38, L39, L40, L41, L42, L43, L44, L45,
                                            L46, L47, L48, L49, L50, L51, L52, L53/*, L54,
                                            L55, L56, L57, L58, L59, L60*/};
  
  public static final int TOTAL_LEVELS = levels.length;
}
